version: "2"

networks:
  artifacts_test:
      name: artifacts_test

    # external: true


services:
  ca-bank:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bank.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.bank.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/bank.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel/crypto-config/peerOrganizations/bank.example.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.bank.example.com
    hostname: ca.bank.example.com
    networks:
      - artifacts_test


  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.1
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=7050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
      - 8443:8443
    networks:
      - artifacts_test
    volumes:
      - ./artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - artifacts_test

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:6984
    networks:
      - artifacts_test

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:7984
    networks:
      - artifacts_test

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:8984
    networks:
      - artifacts_test

  peer0.bank.example.com:
    container_name: peer0.bank.example.com
    hostname: peer0.bank.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=OrgBankMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer0.bank.example.com
      - CORE_PEER_ADDRESS=peer0.bank.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bank.example.com:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.example.com:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - ORDERER_CA=/etc/hyperledger/orderer/tls/ca.crt
      - CORE_CHAINCODE_EXTERNALBUILD_RUNNER=cc-builder
      
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_CHAINCODE_MODE=external
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    
    depends_on:
      - couchdb0
    ports:
      - 7051:7051
      - 8080:8080
    volumes:
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer0.bank.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer0.bank.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./channel/crypto-config/peerOrganizations/bank.example.com/users/Admin@bank.example.com/msp:/etc/hyperledger/crypto/admin/msp
      - ./channel/configtx.yaml:/etc/hyperledger/channel/configtx.yaml
      - ./channel/core.yaml:/etc/hyperledger/channel/core.yaml
      - ./channel/crypto-config.yaml:/etc/hyperledger/channel/crypto-config.yaml
      - /var/run/:/host/var/run/
      # - ./:/etc/hyperledger/
      - ./chaincode:/etc/hyperledger/chaincode
      # - ./artifacts:/etc/hyperledger/chaincode
      - ./peer-scripts:/etc/hyperledger/peer-scripts
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt:/etc/hyperledger/orderer/tls/ca.crt
      - ./artifacts:/etc/hyperledger/artifacts
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer1.bank.example.com/tls/ca.crt:/etc/hyperledger/crypto/peers/peer1/tls/ca.crt
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer2.bank.example.com/tls/ca.crt:/etc/hyperledger/crypto/peers/peer2/tls/ca.crt
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer3.bank.example.com/tls/ca.crt:/etc/hyperledger/crypto/peers/peer3/tls/ca.crt

      - /var/run/:/host/var/run/

    networks:
      - artifacts_test

  peer1.bank.example.com:
    container_name: peer1.bank.example.com
    hostname: peer1.bank.example.com
    extends:
      file: base.yaml
      service: peer-base
    depends_on:
      - couchdb1
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=OrgBankMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer1.bank.example.com
      - CORE_PEER_ADDRESS=peer1.bank.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.bank.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.bank.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.bank.example.com:9051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - ORDERER_CA=/etc/hyperledger/orderer/tls/ca.crt4

      - CORE_CHAINCODE_EXTERNALBUILD_RUNNER=cc-builder
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_CHAINCODE_MODE=external
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

    ports:
      - 8051:8051
      - 8081:8081
    volumes:
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer1.bank.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer1.bank.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./channel/crypto-config/peerOrganizations/bank.example.com/users/Admin@bank.example.com/msp:/etc/hyperledger/crypto/admin/msp
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt:/etc/hyperledger/orderer/tls/ca.crt

      - ./channel/configtx.yaml:/etc/hyperledger/channel/configtx.yaml
      - ./channel/core.yaml:/etc/hyperledger/channel/core.yaml
      - ./channel/crypto-config.yaml:/etc/hyperledger/channel/crypto-config.yaml
      # - ./:/etc/hyperledger/
      - ./chaincode:/etc/hyperledger/chaincode
      # - ./artifacts:/etc/hyperledger/chaincode
      - ./peer-scripts:/etc/hyperledger/peer-scripts
      - ./artifacts:/etc/hyperledger/artifacts
    
      - /var/run/:/host/var/run/
    
    networks:
      - artifacts_test
  
  peer2.bank.example.com:
    container_name: peer2.bank.example.com
    hostname: peer2.bank.example.com
    extends:
      file: base.yaml
      service: peer-base
    depends_on:
      - couchdb2
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=OrgBankMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer2.bank.example.com
      - CORE_PEER_ADDRESS=peer2.bank.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer2.bank.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.bank.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.bank.example.com:10051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - ORDERER_CA=/etc/hyperledger/orderer/tls/ca.crt

      - CORE_CHAINCODE_EXTERNALBUILD_RUNNER=cc-builder
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_CHAINCODE_MODE=external
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    ports:
      - 9051:9051
      - 8082:8082
    volumes:
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer2.bank.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer2.bank.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./channel/crypto-config/peerOrganizations/bank.example.com/users/Admin@bank.example.com/msp:/etc/hyperledger/crypto/admin/msp
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt:/etc/hyperledger/orderer/tls/ca.crt

      - ./channel/configtx.yaml:/etc/hyperledger/channel/configtx.yaml
      - ./channel/core.yaml:/etc/hyperledger/channel/core.yaml
      - ./channel/crypto-config.yaml:/etc/hyperledger/channel/crypto-config.yaml
      - /var/run/:/host/var/run/
      # - ./:/etc/hyperledger/
      - ./chaincode:/etc/hyperledger/chaincode
      # - ./artifacts:/etc/hyperledger/chaincode
      - ./peer-scripts:/etc/hyperledger/peer-scripts
      - ./artifacts:/etc/hyperledger/artifacts

      - /var/run/:/host/var/run/
    networks:
      - artifacts_test

  peer3.bank.example.com:
    container_name: peer3.bank.example.com
    hostname: peer3.bank.example.com
    extends:
      file: base.yaml
      service: peer-base
    depends_on:
      - couchdb3
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=OrgBankMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer3.bank.example.com
      - CORE_PEER_ADDRESS=peer3.bank.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer3.bank.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.bank.example.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank.example.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - ORDERER_CA=/etc/hyperledger/orderer/tls/ca.crt
      
      - CORE_CHAINCODE_EXTERNALBUILD_RUNNER=cc-builder
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_CHAINCODE_MODE=external
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

    ports:
      - 10051:10051
      - 8083:8083
    volumes:
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer3.bank.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./channel/crypto-config/peerOrganizations/bank.example.com/peers/peer3.bank.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./channel/crypto-config/peerOrganizations/bank.example.com/users/Admin@bank.example.com/msp:/etc/hyperledger/crypto/admin/msp
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt:/etc/hyperledger/orderer/tls/ca.crt

      - ./channel/configtx.yaml:/etc/hyperledger/channel/configtx.yaml
      - ./channel/core.yaml:/etc/hyperledger/channel/core.yaml
      - ./channel/crypto-config.yaml:/etc/hyperledger/channel/crypto-config.yaml
      - /var/run/:/host/var/run/
      # - ./:/etc/hyperledger/
      - ./chaincode:/etc/hyperledger/chaincode
      # - ./artifacts:/etc/hyperledger/chaincode
      - ./peer-scripts:/etc/hyperledger/peer-scripts
      - ./artifacts:/etc/hyperledger/artifacts

      - /var/run/:/host/var/run/
    
    networks:
      - artifacts_test
