OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Bank
    Domain: bank.example.com
    EnableNodeOUs: true
    Template:
      Count: 4
      SANS:
        - "localhost"
    Users:
      Count: 1
